### PR TITLE
Refine/fundamention

### PR DESCRIPTION
**Pull request by Hsuchein**

### CODE REVIEW

**Comment by Hsuchein** [comment]
Three modification points:
1. changing variable names
2. checking mechanism
3. deleting redundant files

**Comment by Hsuchein** [comment]
target 3 is done

**Comment by Hsuchein** [comment]
Target 2 is done

Add checking mechanism in `TinkerSystem` class and `Transformer` class

The element order of TinkerSystem has been refined

**Comment by Hsuchein** [comment]
Target 1 file include:
`_tinkersystem.py, transformer.py, _gmxsystem.py, _gmxmolecule.py, _forcefieldtrans.py`
take `_tinkersystem.py` as the reference

the rest reference:
[https://google-styleguide.readthedocs.io/zh-cn/latest/google-python-styleguide/python_style_rules.html#id21](url)

Every `git push` should be done after the `module_test.py` is passed

**Comment by haodonLiu** [comment]
force-push cover mistake return to [8840cef](https://github.com/WanluLigroupUCSD/TinkerModellor/pull/4/commits/8840cefeeacf6a5b70c6a76199b576a7fac71f11)

[577cf4b](https://github.com/WanluLigroupUCSD/TinkerModellor/pull/4/commits/577cf4b354ee9c872db340be8538f235aacc994d)
add .gitignore
repo to target 1
_gmxsystem.py
self.moleculetype -> self.MoleculeType: list[GMXMolecule]
self.moleculetype_num: int -> self.MoleculetypeNum: list[int] = []
self.coordinates:np.array = [] -> self.Coordinates: np.array
self.system_atom_nums:int -> self.SystemAtomNums: int
self.box_size:np.array -> self.BoxSize: np.array
self.box_angles:np.array  -> self.BoxAngles: np.array
self.atom_index: np.array -> self.AtomIndex: np.array
REINDEX attribute above obey alphabetical order

_get_moleculename.py
REINDEX attribute in __init__ obey alphabetical order

_frocefieldtrans.py
self.aggressive -> self.Aggressive: bool
self.force_field_dict -> self.ForceFieldDict: dict[str, dict[str, int]]
self.residue_list -> self.ResidueList: list[str]
self.FFpara -> self.FFParameter: dict

transformer.py
self.transformer_function -> self.TransformerFunction: Callable


recommend to fix the parameter types as mypy report 
[transformer_typecheck.txt](https://github.com/WanluLigroupUCSD/TinkerModellor/files/14901784/transformer_typecheck.txt)

**Pull request merged**
